### ISSUE TITLE
Test Windows Scripts

### ISSUE THREAD

**Issue by kxlieannh** [kxlieannh/cpscripts#1]

**Comment by kxlieannh** [comment]
We will need to test and run these scripts in a VM (Windows Server in cyber.org) to ensure they work. Anyone can run these scripts themselves using these steps: 

### How to execute a script (.ps1)

Navigate to the directory containing your script using cd: 

 `cd C:\Scripts`

Run the script:

`.\myscript.ps1`

Alternative: Provide the full path to the script:

`C:\Scripts\myscript.ps1`

### To create a script:

Create a text file

Copy and paste script

Save file with GitHub name and (.ps1) extension.

**Comment by txmattt** [comment]
Tested windef.ps1, winfire.ps1, winaudit.ps1, winpass.ps1, winlsp.ps1

**Comment by kxlieannh** [comment]
Tested winrdp.ps1 , No issue, README updated.
